#! /usr/bin/env python

import rospy
from nav_msgs.msg import Odometry
from tf.transformations import euler_from_quaternion
from geometry_msgs.msg import Point, Twist
from math import atan2, pi, pow, sqrt
from std_msgs.msg import Empty
from time import time
from sensor_msgs.msg import LaserScan
#initialize values
x = 0.0
y = 0.0
th = 0.0
dist = 0.0
turn = 0.0
vel = 0.0
#Set the goal coordinates
goal = Point()
goal.x = 0
goal.y = 4
sub_goal = Point()
sub_goal.x = sub_goal.y = 0
def find_angle(goal_x,goal_y, x, y):
    #obtain the x,y vector to goal
    inc_x = goal.x - x
    inc_y = goal.y - y
    #use tan to find the angle needed to turn towards the goal
    a = atan2(inc_y, inc_x) #tanx = O/A
    #convert angle to degrees
    a = a*(180/pi)
    return a

def find_goal(goalx,goaly,x,y):
    #obtain the vector distance to goal
    vect = sqrt(pow((goalx -x),2) + pow((goaly-y),2))
    print vect
    return ("vect: %s" %(vect))

def check_ranges(distance):
    if distance < 0.5:
        return False
    return True
def steering(data):
    global goal
    global dist
    #safety distance
    front = data.ranges[100:412]
    dist = min(front)
    #one = left seven = right
    seven = data.ranges[100:145]
    six = data.ranges[146:207]
    five = data.ranges[208:240]
    four = data.ranges[241:271]
    three = data.ranges[272:304]
    two = data.ranges[305:366]
    one = data.ranges[367:412]
    arr = [one, two, three, four, five, six, seven]
    i = 0
    predict = Point()
    predict.x = predict.y = 0
    best_path = Point()
    best_path.x = best_path.y = 0
    best_count = 1
    if(check_sub_goal() == True):
        for x in range(7):
            if check_ranges(min(arr[i]))==True:
                print ("%s is true" %(i))
                predict.x = predict_path(x, y, i).x
                predict.y = predict_path(x,y,y).y
                print predict
                if best_path.x == best_path.y == 0:
                    best_path.x = predict.x
                    best_path.y = predict.y
                elif find_goal(goal.x, goal.y, predict.x, predict.y) < find_goal(goal.x,goal.y,best_path.x,best_path.y):
                    best_path.x = predict.x
                    best_path.y = best_path.y
                    best_count = i+1
            i = i + 1
            #print best_count
        sub_goal.x = best_path.x
        sub_goal.y = best_path.y
    #print best_path

def predict_path(xp, yp, index):
    pred = Point()
    if index == 1:
        yp = yp + 1.503
        xp = xp + 1.319
    if index == 2:
        yp = yp + 1
        xp = xp + 1.732
    if index == 3:
        yp = yp + 0.333
        xp = xp + 1.972
    if index == 4:
        yp = yp + 0
        xp = xp + 2
    if index == 5:
        yp = yp - 0.333
        xp = xp + 1.972
    if index == 6:
        yp = yp - 1
        xp = xp + 1.732
    if index == 7:
        yp = yp - 1.503
        xp = xp + 1.319
    pred.x = xp
    pred.y = yp
    return pred
def check_sub_goal():
    dx = sub_goal.x - x
    dy = sub_goal.y - y
    if sub_goal.x == sub_goal.y == 0:
        return True
    if (-0.1 < dx < 0.1) and (-0.1 < dy < 0.1):
        sub_goal.x = 0
        sub_goal.y = 0
        return True
    return False

def find_goal(goalx,goaly,xp,yp):
    #obtain the vector distance to goal
    return sqrt(pow((goalx -xp),2) + pow((goaly-yp),2))
#Odometry callback
def newOdon(msg):
#use global variables
    global x
    global y
    global th
#obtain the xy coordinates of the robot from odometry
    x = msg.pose.pose.position.x
    y = msg.pose.pose.position.y
    rot_q = msg.pose.pose.orientation
#obtain the angle 'yaw' using a quaternion to euler converter
    (roll, pitch, th) = euler_from_quaternion([rot_q.x, rot_q.y, rot_q.z, rot_q.w])
#convert the angle to degrees
    #th = atan2(y,x)
    th = th*(180/pi)
    #print th
#set up nodes
rospy.init_node("speed_controller", anonymous = True)
sub = rospy.Subscriber("/odom", Odometry, newOdon)
pub = rospy.Publisher('/cmd_vel_mux/input/teleop', Twist, queue_size =1)
speed = Twist()
#opub = rospy.Publisher("odom", Odometry, queue_size =1)
# set up the odometry reset publisher
reset_odom = rospy.Publisher('/mobile_base/commands/reset_odometry', Empty, queue_size=10)
scan_sub = rospy.Subscriber('/scan', LaserScan, steering)
# reset odometry values (these messages take a few iterations to get through)
timer = time()
while time() - timer < 0.25:
    reset_odom.publish(Empty())
r = rospy.Rate(5)
#Main method
while not rospy.is_shutdown():
#obtain the x,y vector to goal
    if(sub_goal.x == 0 == sub_goal.y):
        sub_goal.x = goal.x
        sub_goal.y = goal.y
    print ("subx: %s suby: %s" % (sub_goal.x, sub_goal.y))
    inc_x = sub_goal.x - x
    inc_y = sub_goal.y - y
#use tan to find the angle needed to turn towards the goal
    angle_to_goal = atan2(inc_y, inc_x)
#convert angle to degrees
    angle_to_goal = angle_to_goal*(180/pi)
#find the difference between the angle of the bot and angle needed to turn
    angle = angle_to_goal - th
    #print ("x: %s y: %s" % (inc_x, inc_y))
#check if the bot is within a suitable angle to the goal
    if angle > 1 or angle < -1:
        print th
        speed.linear.x = 0.0
        if(angle < -1):
            speed.angular.z = -0.5
        elif angle > 1:
            speed.angular.z = 0.5
    if (-1 <= angle <= 1):
        speed.linear.x = 0.2
        speed.angular.z = 0
#check if the bot has reached the goal
    if (-0.1 < inc_x < 0.1) and (-0.1 < inc_y < 0.1):
	    speed.linear.x = 0
	    speed.angular.z = 0
    if (-0.1 <=(x - goal.x)<=0.1 and -0.1 <= (y - goal.y) <=0.1):
        print "reached"
        speed.linear.x = 0
        #r.sleep()
    if dist < 0.2:
        speed.linear.x = -0.1
        print "nuh uh: %s" %(dist)
    pub.publish(speed)
    r.sleep()
rospy.spin()
